### PR TITLE
GUI redesign and to-do list

### PR DESCRIPTION
**Pull request by Neoloopy**
**Changing the layout of the GUI (Can still be changed uwu)**

**Color Palette used:**
#EE4540 (Not yet used, meant for labels)
#C72C41 (Used in texts)
#801336 (Not yet used, might use for mid-tones to create depth)
#510A32 (Used in Entry, Textbox, and Listbox background)
#2D142C (Used in the background)

### New features!
-  To-do list
- Entry to let people add tasks
-  Added a to-do list, insert, and delete button

### CODE REVIEW

**Comment by nafumie** [comment]
image
thats a lot of issues wtf HAHAHAHAH

**Review by nafumie — APPROVED** [review]
maybe clean up the tab indentations to spaces so sider will stop complaining but it looks good to me

**Comment by angelofallars** [comment]
My changes were merged into this, all checks passed so we can merge

**Comment by nafumie** [comment]
> My changes were merged into this, all checks passed so we can merge

yup just waiting for sider to finish

**Review by nafumie — APPROVED** [review]
very daijobu

**Pull request merged**
